name: Open Research Core
nickname: roc
description: A lightweight open-source framework for the development of domain-specific collaborative research systems.
url: http://openresearchcore.org
author: Chris Chapman
author_email: chris@pentandra.com
sponsor:
  name: Pentandra Research Solutions, Inc.
  url: http://pentandra.com
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
kramdown:
  use_coderay: true
trackingId: UA-39675649-1
